ops: log the error to console

diff --git a/.github/workflows/CD.yml b/.github/workflows/CD.yml
--- a/.github/workflows/CD.yml
+++ b/.github/workflows/CD.yml
@@ -29,23 +29,23 @@ jobs:
 
     - name: Build Docker image
       id: docker_build
-      continue-on-error: true
       run: |
-        # Capture the build output in a variable
-        ERROR_OUTPUT=$(docker compose build 2>&1)
-        BUILD_EXIT_CODE=$?
+        docker compose build
+        ## Capture the build output in a variable
+        #ERROR_OUTPUT=$(docker compose build 2>&1)
+        #BUILD_EXIT_CODE=$?
 
-        echo "$ERROR_OUTPUT"
+        #echo "$ERROR_OUTPUT"
         
-        # Store the error output for later use
-        echo "BUILD_ERROR<<EOF" >> $GITHUB_ENV
-        echo "$ERROR_OUTPUT" >> $GITHUB_ENV
-        echo "EOF" >> $GITHUB_ENV
+        ## Store the error output for later use
+        #echo "BUILD_ERROR<<EOF" >> $GITHUB_ENV
+        #echo "$ERROR_OUTPUT" >> $GITHUB_ENV
+        #echo "EOF" >> $GITHUB_ENV
         
         # Store the build status
         echo "BUILD_EXIT_CODE=$BUILD_EXIT_CODE" >> $GITHUB_ENV
-        # Exit with the original build exit code
-        exit $BUILD_EXIT_CODE
+        ## Exit with the original build exit code
+        #exit $BUILD_EXIT_CODE
 
     - name: Push Docker image
       if: success() && steps.docker_build.outcome == 'success'
@@ -60,9 +60,9 @@ jobs:
           
           const errorLog = process.env.BUILD_ERROR || 'Docker build or push failed';
           
-          let errorMessage = '❌ Build failed!\n\n';
+          // let errorMessage = '❌ Build failed!\n\n';
           
-          errorMessage += `Error details:\n\`\`\`\n${errorLog}\n\`\`\``;
+          // errorMessage += `Error details:\n\`\`\`\n${errorLog}\n\`\`\``;
           
           
           // Add comment to PR
@@ -70,7 +70,8 @@ jobs:
             owner,
             repo,
             issue_number: number,
-            body: errorMessage
+            body: " "
+            // body: errorMessage
           });
           
           // Close PR
