ops: test PR

diff --git a/.github/workflows/CI.yml b/.github/workflows/CI.yml
--- a/.github/workflows/CI.yml
+++ b/.github/workflows/CI.yml
@@ -83,14 +83,14 @@ jobs:
         continue-on-error: true
         run: |
           export TERM=xterm
-          touch /tmp/TestResult.txt
-          npx cypress run | awk '/\(Run Finished\)/{flag=1} flag' | tee /tmp/TestResult.txt
-          export OUTPUT="$(cat /tmp/TestResult.txt)"
-          cat /tmp/TestResult.txt
+          touch /tmp/output.txt
+          npx cypress run | awk '/\(Run Finished\)/{flag=1} flag' | tee /tmp/output.txt
+          export OUTPUT="$(cat /tmp/output.txt)"
+          cat /tmp/output.txt
       - name: Debug - Show file content
         run: |
-          echo "Checking if TestResult.txt exists:"
-          cat /tmp/TestResult.txt || echo "File not found"
+          echo "Checking if output.txt exists:"
+          cat /tmp/output.txt || echo "File not found"
       - name: Comment Test Results on PR
         if: always() && github.event_name == 'pull_request'
         uses: actions/github-script@v7
@@ -101,17 +101,17 @@ jobs:
             
             let testOutput = 'No test results found';
             try {
-              testOutput = fs.readFileSync('/tmp/TestResult.txt', 'utf8');
+              testOutput = fs.readFileSync('/tmp/output.txt', 'utf8');
             } catch (error) {
               testOutput = `Error: ${error} ${OUTPUT}`
               //console.error('Error reading test results:', error);
             }
 
             const message = `**Cypress Test Results**\n\n` +
-              `${fs.readFileSync('/tmp/TestResult.txt', 'utf8')}` +
+              `${fs.readFileSync('/tmp/output.txt', 'utf8')}` +
               `Test\n` +
               `\`\`\`\n${testOutput}\n\`\`\`\n` +
-              `\`\`\`\n${fs.readFileSync('/tmp/TestResult.txt', 'utf8')}\n\`\`\`\n` +
+              `\`\`\`\n${fs.readFileSync('/tmp/output.txt', 'utf8')}\n\`\`\`\n` +
               `[View Full Report](${process.env.GITHUB_SERVER_URL}/${process.env.GITHUB_REPOSITORY}/actions/runs/${process.env.GITHUB_RUN_ID})`;
 
             await github.rest.issues.createComment({
